### PR TITLE
chore: Add emoji to readme

### PR DESCRIPTION
**Pull request by jsoref**
image

### CODE REVIEW

**Review by shogo82148 — APPROVED** [review]
LGTM

**Comment by jsoref** [comment]
Oddly, it looks great here:
https://github.com/marketplace/actions/setup-reviewdog

But so far it doesn't appear to have updated here:
https://github.com/marketplace/manage

I'm not sure if that's a caching thing.

**Comment by shogo82148** [comment]
Creating a new release might be required.
I'll try it.

**Comment by shogo82148** [comment]
https://github.com/marketplace/manage
image

it looks fine 🐶

**Comment by jsoref** [comment]
Hmm, the 🐶 is in a different place, so apparently it's different metadata?

Shrug. it's definitely better now, that's all I care about :-).

**Pull request merged**
